### ISSUE TITLE
Revelry - Time Tracking - Setup Project

### ISSUE THREAD

**Issue by Samkeer1** [revelrylabs/onepagesale#47]
## Background
We use Airtable to view resourcing and track hours:
- Spending Time: http://wiki.revelry.co/index.php/Spending_time
- Viewing Time: http://wiki.revelry.co/index.php/Viewing_time
- Time Capture: https://airtable.com/shrV4tXD46VGk42JM?prefill_Name=Aline%20Adams&prefill_Project=TSS%20Phase%201&prefill_Category=Project%20Planning
- Project Update: https://airtable.com/shrLVbmhuLXv96qPP

If a project has not yet been setup, then @thomasknoll will need to create the project.

## Scenario: Add Project to Airtable 
Given I am a Reveler
- [ ] When I view any of the links listed above
- [ ] Then I see the new project
- [ ] When I do not see the new project
- [ ] Then I assign Thomas to this ticket
- [ ] And Thomas adds the project to Airtable
