### ISSUE TITLE
Revelry - Time Tracking - Setup Airtable Project

### ISSUE THREAD

**Issue by Samkeer1** [revelrylabs/onepagesale#52]
## Background
[Airtable](https://airtable.com/shrV4tXD46VGk42JM) is the time tracking tool currently used at Revelry. If a project has not yet been setup, then fill out the [New Project Kickoff](https://airtable.com/shr7JeyJCsyEPqO0f) form.

## Scenario: Look for Project in Airtable
Given I am a Reveler
- [ ] When I log my hours
- [ ] Then I see the new project
- [ ] When I do not see the new project
- [ ] Then I fill out the [New Project Kickoff](https://airtable.com/shr7JeyJCsyEPqO0f) form
